version: '2'
services:
  app:
    container_name: ${DOCKER_IMAGE_NAME}_app
    hostname: ${DOCKER_IMAGE_NAME}_app
    restart: always
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - ${DOCKER_APP_PORT}:80
    volumes:
      - ${DOCKER_APP_DIR}:/var/www/html
